FROM alpine:3.20
 
USER root
RUN apk update && \
    apk add --no-cache \
        bash \
        ca-certificates \
        curl \
        git \
	sudo
 
RUN adduser -D -g '' -u 1000 vf-user && \
    echo "vf-user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
 
ENV LANG en_US.UTF-8
USER vf-user
